---
application:
  name: "mybroker"
  project: "mqtt.ranchonds.ml"
  organization: "QoveryCommunity"
  port: 1883
databases:
- type: "MONGODB"
  name: "myBrokerBD"
  version: "4.4"
routers:
- name: "main-mybroker"
  custom_domains:
    - branch: "main"
      domain: "mqtt.ranchonds.ml"
  routes:
  - application_name: "mybroker"
    paths:
    - "/*"
